name: Deploy to Scalingo

on:
  push:
    branches:
      - prod
  workflow_run:
    workflows: ["Terraform Scalingo Provision"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Scalingo CLI
        run: |
          curl -O https://cli-dl.scalingo.com/install && bash install

      - name: Authenticate with Scalingo
        env:
          SCALINGO_TOKEN: ${{ secrets.SCALINGO_TOKEN }}
        run: |
          echo "$SCALINGO_TOKEN" | scalingo login --ssh=false

      - name: Deploy to Scalingo
        run: |
          cd app
          scalingo --app mon-application-terraform --region osc-fr1 deploy 