name: Terraform Scalingo Provision and Deploy

on:
  push:
    branches:
      - prod

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.extract_app_name.outputs.app_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        # with:
        #   terraform_version: ">= 1.0.0" # Optionnel

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init
        env:
          TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }} # Optionnel
          TF_CLOUD_WORKSPACE: ${{ secrets.TF_CLOUD_WORKSPACE }} # Optionnel

      - name: Plan Terraform
        run: |
          cd terraform
          terraform plan
        env:
          TF_VAR_scalingo_token: ${{ secrets.SCALINGO_TOKEN }}

      - name: Apply Terraform
        run: |
          cd terraform
          terraform apply -auto-approve
        env:
          TF_VAR_scalingo_token: ${{ secrets.SCALINGO_TOKEN }}
          
      - name: Extract app name
        id: extract_app_name
        run: |
          cd terraform
          APP_NAME=$(terraform output -raw app_name)
          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT

  deploy:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Scalingo
        uses: kolok/deploy-to-scalingo@v1
        with:
          scalingo_token: ${{ secrets.SCALINGO_TOKEN }}
          app_name: ${{ needs.terraform.outputs.app_name }} 